### ISSUE TITLE
About render

### ISSUE THREAD

**Issue by YHJCTR** [zyqz97/GP-NeRF#12]
你好作者，感谢你开源了论文中的代码，我想问一下如果我想结果可视化的话我应该怎么做？给定几个位姿渲染几张图片就行

**Comment by wanger-666** [comment]
+1

**Comment by zyqz97** [comment]
你好，最简单的方式是，把给定的位姿按照mega-nerf的文件格式存储，放到dataset/val/metadata路径下，然后使用eval代码进行渲染，读取val文件夹下的位姿文件，渲染对应的图像（注意这里没有对应的image，需要修改[代码](https://github.com/zyqz97/GP-NeRF/blob/main/gp_nerf/runner_gpnerf.py#L483)，或是直接定义成一个空白图像）。

**Comment by YHJCTR** [comment]
okok，感谢
