### ISSUE TITLE
Adding a License 

### ISSUE THREAD

**Issue by alexwitt23** [zyqz97/GP-NeRF#2]
Hi, thank you for releasing your code to accompany your paper. Pardon me if I've missed something, but I don't seem to see a `LICENSE` associated with this repository. Would you please be able to add one? Both Mega-NeRF and torch-ngp use MIT license which might also make sense to use here. Thank you!

**Comment by zyqz97** [comment]
> Hi, thank you for releasing your code to accompany your paper. Pardon me if I've missed something, but I don't seem to see a `LICENSE` associated with this repository. Would you please be able to add one? Both Mega-NeRF and torch-ngp use MIT license which might also make sense to use here. Thank you!

Thank you!
