### ISSUE TITLE
Does this approach use submodules similarily to Mega-nerf?

### ISSUE THREAD

**Issue by SamiAouad** [zyqz97/GP-NeRF#3]
Hello, thanks for the great job.

I wanted to ask if this approach uses submodules similarly to the Mega-NeRF, if yes what replaced the `merge_submodules.py` since I noticed that both approaches uses similar training phase.

Thanks in advance.

**Comment by zyqz97** [comment]
We use one model to represent the scene instead of using submodules, thus it doesn't need 'merge_submodules'. Thanks.
