### ISSUE TITLE
bg_nerf does not work

### ISSUE THREAD

**Issue by Fangkang515** [zyqz97/GP-NeRF#5]
Thanks for your great work.

I have a confusion about the setting of foreground and background. The default bg_nerf is off in the [code](https://github.com/zyqz97/GP-NeRF/blob/main/gp_nerf/train.py#L27), which seems inconsistent with the paper.
Therefore I set bg_nerf=true, but I found that it did not improve the results. Is there a critical step I have overlooked? 

Looking forward to your reply. 
Thanks again.

**Comment by zyqz97** [comment]
> 
The ‘bg_nerf’ is discarded in our code. The background modeling is set to be used by default in this repo. Please refer to [L75](https://github.com/zyqz97/GP-NeRF/blob/main/gp_nerf/models/gp_nerf.py#L75) & [L164](https://github.com/zyqz97/GP-NeRF/blob/main/gp_nerf/models/gp_nerf.py#L164)
