### ISSUE TITLE
Hello, do you have a script for merging? 

### ISSUE THREAD

**Issue by lhc991025** [zyqz97/GP-NeRF#9]

**Comment by zyqz97** [comment]
We used one model to represent the scene instead of using submodules like mega-nerf, so there is no need to merge. You can refer to https://github.com/cmusatyalab/mega-nerf/blob/main/scripts/merge_submodules.py to find the merging script.

**Comment by lhc991025** [comment]
> We used one model to represent the scene instead of using submodules like mega-nerf, so there is no need to merge. You can refer to https://github.com/cmusatyalab/mega-nerf/blob/main/scripts/merge_submodules.py to find the merging script.

Yes, your work did not involve chunking. Thank you very much for your outstanding work. Can you provide a tutorial on customizing datasets

**Comment by zyqz97** [comment]
> > We used one model to represent the scene instead of using submodules like mega-nerf, so there is no need to merge. You can refer to https://github.com/cmusatyalab/mega-nerf/blob/main/scripts/merge_submodules.py to find the merging script.
> 
> Yes, your work did not involve chunking. Thank you very much for your outstanding work. Can you provide a tutorial on customizing datasets

The Mega-NeRF repo provides a tutorial on customizing datasets. Please kindly refer to [this link](https://github.com/cmusatyalab/mega-nerf?tab=readme-ov-file#custom-data).
